### ISSUE TITLE
HTML UI

### ISSUE THREAD

**Issue by jakevolkman** [OSU-CS361-W17/group1_project1#3]
Hey guys so when I accepted the pull request from Daniel, I guess it didn't save his updated UI? I pulled again from the master and confirmed by downloading index.html separately. We should confirm if this is an issue with Daniel's or my repository.
Thanks.

**Comment by dmkato** [comment]
I just checked the group master html, and it appears to include my changes

**Comment by jakevolkman** [comment]
Yeah I fixed it. Andrew was pushing to the master by accident. I changed his origin remote to his fork and pushed the changes back to the master.

**Comment by dmkato** [comment]
Oh got you, Ill go ahead and close this issue then.
